feat: org member management
hu-tao-supremacy/frontend pull request #76
Opened 2021-04-25 10:01 UTC by boompikachu

2021-04-25 10:47 UTC, boompikachu commented
If it's not important, pls let it pass. No time

2021-04-25 14:28 UTC, poom-kitti requested changes
Fix pls

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/MemberManagementPage.vue
> +    <div class="content-max-width w-full mt-4 mb-10">
Why mb-10?

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +  <h1 class="font-heading text-4xl">{{ title }}</h1>
Put in page better

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +      placeholder="Descending alphabets"
I do not think you need this

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +      @update:modelValue="handleSelectSort"
Why do not use v-model to get the value of optionValues? v-model="sortOption"

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +  <div className="p-3 bg-white // rounded-2xl w-full // font-medium">
There is no font-medium avail. for both manrope and inter krub. Pls look at public/index.html to see import

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +              </div>
Use user-profile in commons/UI

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +              </base-icon>
Cover tag with base transparent button

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +      type: Object as PropType<Record<string, any>[]>
Why any? Isn't this list of users?

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +    console.log(props.data);
Delete pls

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/MemberManagementPage.vue
> +      lastName: null,
Is it needed?

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +    });
Is this really needed?

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +    });
Use Fuse.js

2021-04-25 14:28 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +    };
Not needed. Use v-model instead

2021-04-25 16:01 UTC, boompikachu commented on src/modules/organization/member-management/table/Table.vue
> +    });
It is needed

2021-04-26 03:56 UTC, poom-kitti approved these changes
LGTM after change

2021-04-26 03:56 UTC, poom-kitti commented on public/index.html
> +        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Manrope:wght@700&display=swap"
Do not add new font

2021-04-26 03:56 UTC, poom-kitti commented on public/index.html
> +        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Manrope:wght@700&display=swap"
If UX/UI does not comply with font, tell them b/c we already agree to only have this much font.

2021-04-26 03:56 UTC, poom-kitti commented on src/modules/organization/member-management/table/Table.vue
> +                <base-icon class="cursor-pointer">
Does not need class cursor-pointer anymore

2021-04-26 03:56 UTC, poom-kitti commented on src/modules/organization/member-management/table/use-table/index.ts
> +          break;
Why have when you do not have these cases?

2021-04-26 06:21 UTC, poom-kitti commented on public/index.html
> +      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Manrope:wght@700&display=swap"
Delete font 500

2021-04-26 06:21 UTC, poom-kitti commented on src/modules/organization/member-management/table/use-table/index.ts
> +      }
Note: Fuse is useless here because it is sorted by similarity, but then you override it to sort by ascending/descending again

2021-04-26 06:50 UTC, boompikachu commented
Put fuse sort and selection dropdown in backlog

2021-04-26 06:51 UTC, merged